### ISSUE TITLE
Inaccurate stats and AnswerDistribution for Multi Select questions

### ISSUE THREAD

**Issue by etenoch** [qlicker/qlicker#77] opened 2017-03-15 01:25 UTC
Files Involved: QuestionDisplay.jsx & AnswerDistribution.jsx

Pre-conditions:
- Multi select question
- student has submitted a response with multiple options
- Attempt > 1

Bug: Graph does not show correct number of responses for answers with multiple selected

**Comment by ReckoningReckoner** [comment] 2018-01-16 15:04
I cannot reproduce this anymore. I believe it was fixed in: e41a714fe6e8b

**Closed by ReckoningReckoner** 2018-01-16 15:04 UTC
Labels: bug
